console.log("1st Statement");
console.log("2nd Statement");
debugger;
console.log("3rd Statement");
console.log("4th Statement");
debugger;
console.log("5th Statement");
console.log("6th Statement");
debugger;
console.log("7th Statement");
console.log("8th Statement");
debugger;
console.log("9th Statement");
console.log("10th Statement");
